import { Injectable, signal } from '@angular/core';

export type Lang = 'tr' | 'en' | 'ru';

const T: Record<Lang, Record<string, string>> = {

  /* ══════════════════════════════════════ TÜRKÇE ══════════════════════════════════════ */
  tr: {
    // Nav
    'nav.home':         'Ana Sayfa',
    'nav.appointments': 'Randevular',
    'nav.staff':        'Personel',
    'nav.services':     'Hizmetler',
    'nav.customers':    'Müşteriler',
    'nav.settings':     'Ayarlar',
    'nav.reports':      'Raporlar',

    // Page titles (header)
    'page.dashboard':    'Dashboard',
    'page.appointments': 'Randevular',
    'page.staff':        'Personel',
    'page.services':     'Hizmetler',
    'page.customers':    'Müşteriler',
    'page.settings':     'Ayarlar',
    'page.reports':      'Raporlar',

    // Header
    'header.system': 'Sistem Aktif',

    // Dashboard
    'dashboard.subtitle':       'Hoş geldiniz! İşte bugünün özeti.',
    'dashboard.newAppointment': '+ Yeni Randevu',
    'dashboard.todayAppts':     'Bugünkü Randevular',
    'dashboard.viewAll':        'Tümünü Gör →',
    'dashboard.quickActions':   'Hızlı İşlemler',
    'dashboard.noAppts':        'Bugün randevu bulunmuyor.',
    'dashboard.q1':             'Yeni Randevu',
    'dashboard.q1sub':          'Randevu oluştur',
    'dashboard.q2':             'Müşteri Ekle',
    'dashboard.q2sub':          'Yeni müşteri kaydı',
    'dashboard.q3':             'Personel Ekle',
    'dashboard.q3sub':          'Yeni personel kaydı',
    'dashboard.q4':             'Hizmet Ekle',
    'dashboard.q4sub':          'Yeni hizmet tanımla',
    'stat.todayAppts':          'Bugünkü Randevular',
    'stat.totalCustomers':      'Toplam Müşteri',
    'stat.totalStaff':          'Toplam Personel',
    'stat.totalServices':       'Toplam Hizmet',
    'stat.todayRevenue':        'Bugünkü Gelir',

    // Appointment statuses
    'status.pending':   'Bekliyor',
    'status.confirmed': 'Onaylandı',
    'status.completed': 'Tamamlandı',
    'status.cancelled': 'İptal',
    'status.noShow':    'Gelmedi',

    // Settings — genel
    'settings.title':    'Ayarlar',
    'settings.subtitle': 'Salon ve hesap ayarlarınızı yönetin',
    'settings.logout':   'Çıkış Yap',

    // Settings — Salon Bilgileri
    'settings.salon.card':         'Salon Bilgileri',
    'settings.salon.cardSub':      'Müşterilerinizin göreceği salon bilgileri',
    'settings.salon.logo':         'Salon Logosu',
    'settings.salon.logoHint':     'JPG, PNG veya WebP · Maks 5MB',
    'settings.salon.logoUploading':'Yükleniyor...',
    'settings.salon.logoChange':   'Logoyu Değiştir',
    'settings.salon.logoSelect':   'Logo Seç',
    'settings.salon.name':         'Salon Adı *',
    'settings.salon.namePh':       'Salon adınız',
    'settings.salon.phone':        'Telefon',
    'settings.salon.phonePh':      '05XX XXX XX XX',
    'settings.salon.phoneErr':     'Geçerli bir telefon numarası girin (05XX XXX XX XX)',
    'settings.salon.whatsapp':     'WhatsApp Bildirim Numarası',
    'settings.salon.whatsappPh':   '05XX XXX XX XX',
    'settings.salon.whatsappHint': 'Yeni randevu taleplerinde bu numaraya WhatsApp bildirimi gönderilir.',
    'settings.salon.address':      'Adres',
    'settings.salon.addressPh':    'Salon adresiniz',
    'settings.salon.themeColor':   'Tema Rengi',
    'settings.salon.themeHint':    'Müşteri randevu sayfanızın tema rengini belirleyin',
    'settings.salon.bookingLink':  'Müşteri Booking Linki',
    'settings.salon.save':         'Kaydet',
    'settings.salon.saving':       'Kaydediliyor...',
    'settings.salon.saved':        'Salon bilgileri güncellendi!',
    'settings.salon.custom':       'Özel',

    // Settings — Fotoğraflar
    'settings.photos.card':    'Salon Fotoğrafları',
    'settings.photos.cardSub': 'Müşterilerin booking sayfasında göreceği fotoğraflar (maks. 6)',
    'settings.photos.add':     'Fotoğraf Ekle',

    // Settings — Profil
    'settings.profile.card':    'Profil Bilgileri',
    'settings.profile.cardSub': 'Hesap bilgileriniz',

    // Settings — Şifre
    'settings.password.card':        'Şifre Değiştir',
    'settings.password.cardSub':     'Hesap güvenliğiniz için şifrenizi güncelleyin',
    'settings.password.current':     'Mevcut Şifre',
    'settings.password.new':         'Yeni Şifre',
    'settings.password.confirm':     'Yeni Şifre Tekrar',
    'settings.password.change':      'Şifreyi Değiştir',
    'settings.password.changing':    'Değiştiriliyor...',
    'settings.password.changed':     'Şifre başarıyla değiştirildi!',
    'settings.password.rule.minLen': 'En az 8 karakter',
    'settings.password.rule.upper':  'En az 1 büyük harf (A-Z)',
    'settings.password.rule.number': 'En az 1 rakam (0-9)',
    'settings.password.noMatch':     'Şifreler eşleşmiyor.',
    'settings.password.tooShort':    'Şifre en az 8 karakter olmalı.',

    // Settings — Booking linki
    'settings.booking.card':    'Müşteri Randevu Linki',
    'settings.booking.cardSub': 'Bu linki müşterilerinizle paylaşın',
    'settings.booking.preview': 'Önizle',

    // Reports
    'reports.title':           'Raporlar',
    'reports.subtitle':        'Kazanç ve randevu analizi',
    'reports.startDate':       'Başlangıç Tarihi',
    'reports.endDate':         'Bitiş Tarihi',
    'reports.totalEarnings':   'Toplam Kazanç',
    'reports.avgPerAppt':      'Ort. Randevu Başına',
    'reports.thisMonth':       'Bu Ay',
    'reports.thisWeek':        'Bu Hafta',
    'reports.appt':            'randevu',
    'reports.byStaff':         'Personele Göre Kazanç',
    'reports.byService':       'Hizmet Bazında Kazanç',
    'reports.colStaff':        'Personel',
    'reports.colService':      'Hizmet',
    'reports.colTotal':        'Toplam Kazanç',
    'reports.colAppts':        'Randevu',
    'reports.colAvg':          'Ortalama',
    'reports.colPrice':        'Fiyat',
    'reports.colSales':        'Satış Sayısı',
    'reports.noData':          'Veri bulunmuyor',
    'reports.byCurrency':      'Para Birimine Göre Kazanç',
    'reports.rateDate':        'Kur tarihi',
    'reports.grandTotal':      'Genel Toplam (TRY)',

    // Nav sections
    'nav.section.main':  'ANA MENÜ',
    'nav.section.other': 'DİĞER',
    'nav.logout':        'Çıkış Yap',

    // Common
    'common.loading':          'Yükleniyor...',
    'common.copy':             'Kopyala',
    'common.copied':           'Kopyalandı',
    'common.active':           'Aktif',
    'common.inactive':         'Pasif',
    'common.cancel':           'İptal',
    'common.save':             'Kaydet',
    'common.saving':           'Kaydediliyor...',
    'common.update':           'Güncelle',
    'common.edit':             'Düzenle',
    'common.actions':          'İşlemler',
    'common.status':           'Durum',
    'common.phone':            'Telefon',
    'common.fullName':         'Ad Soyad *',
    'common.fullNameRequired': 'Ad soyad zorunludur.',
    'common.date':             'Tarih',
    'common.closed':           'Kapalı',
    'common.notes':            'Notlar',
    'common.email':            'Email',
    'common.min':              'dk',
    'common.hr':               'sa',
    'common.error':            'Hata oluştu.',

    'color.black':  'Siyah',
    'color.navy':   'Lacivert',
    'color.purple': 'Mor',
    'color.blue':   'Mavi',
    'color.green':  'Yeşil',
    'color.red':    'Kırmızı',
    'color.orange': 'Turuncu',
    'color.pink':   'Pembe',
    'color.brown':  'Kahve',
    'color.gray':   'Gri',

    // Staff
    'staff.add':          '+ Personel Ekle',
    'staff.registered':   'personel kayıtlı',
    'staff.empty':        'Henüz personel eklenmedi',
    'staff.emptyHint':    'İlk personeli eklemek için butona tıklayın.',
    'staff.new':          'Yeni Personel',
    'staff.edit':         'Personel Düzenle',
    'staff.bio':          'Biyografi',
    'staff.colBio':       'Bio',
    'staff.workingHours': 'Çalışma Saatleri',

    // Services
    'services.add':          '+ Hizmet Ekle',
    'services.registered':   'hizmet tanımlı',
    'services.empty':        'Henüz hizmet eklenmedi',
    'services.emptyHint':    'İlk hizmeti eklemek için butona tıklayın.',
    'services.new':          'Yeni Hizmet',
    'services.edit':         'Hizmet Düzenle',
    'services.nameLbl':      'Hizmet Adı *',
    'services.nameRequired': 'Hizmet adı zorunludur.',
    'services.duration':     'Süre (Dakika) *',
    'services.price':        'Fiyat',
    'services.priceOpt':     '(opsiyonel)',
    'services.currency':     'Para Birimi',
    'services.color':        'Renk',

    // Appointments
    'appt.new':           '+ Yeni Randevu',
    'appt.count':         'randevu listeleniyor',
    'appt.empty':         'Randevu bulunamadı',
    'appt.emptyHint':     'Seçili tarih için randevu bulunmuyor.',
    'appt.emptyCalendar': 'Bu tarih için randevu yok',
    'appt.colTime':       'Saat',
    'appt.colCustomer':   'Müşteri',
    'appt.colService':    'Hizmet',
    'appt.colDuration':   'Süre',
    'appt.create':        'Randevu Oluştur',
    'appt.chooseTime':    'Saat Seç *',
    'appt.loadingSlots':  'Müsait saatler yükleniyor...',
    'appt.allStaff':      'Tüm Personel',
    'appt.chooseDate':    'Tarih Seç',
    'appt.customer':      'Müşteri *',
    'appt.staff':         'Personel *',
    'appt.service':       'Hizmet *',
    'appt.date':          'Tarih *',
    'appt.notePh':        'Randevu notları...',

    // Customers
    'customers.add':           '+ Müşteri Ekle',
    'customers.registered':    'müşteri kayıtlı',
    'customers.searchPh':      'İsim, telefon veya email ile ara...',
    'customers.noResults':     'Sonuç bulunamadı',
    'customers.notFoundFor':   'için müşteri bulunamadı.',
    'customers.empty':         'Henüz müşteri eklenmedi',
    'customers.emptyHint':     'İlk müşteriyi eklemek için butona tıklayın.',
    'customers.new':           'Yeni Müşteri',
    'customers.edit':          'Müşteri Düzenle',
    'customers.colCustomer':   'Müşteri',
    'customers.colVisits':     'Toplam Ziyaret',
    'customers.visit':         'ziyaret',
    'customers.phone':         'Telefon *',
    'customers.phoneRequired': 'Telefon zorunludur.',
    'customers.emailInvalid':  'Geçerli bir email giriniz.',
    'customers.notePh':        'Müşteri hakkında notlar...',

    // Appointment Status (public)
    'apptStatus.notFound':       'Randevu Bulunamadı',
    'apptStatus.notFoundMsg':    'Randevu bulunamadı.',
    'apptStatus.saveLink':       '📎 Bu linki kaydedin',
    'apptStatus.saveLinkDesc':   'Randevu onay durumunuzu buradan takip edebilirsiniz.',
    'apptStatus.copyLink':       '📋 Linki Kopyala',
    'apptStatus.pending.text':   'Onay Bekleniyor',
    'apptStatus.pending.sub':    'Salon onayı bekleniyor, kısa süre içinde bilgilendirileceksiniz.',
    'apptStatus.confirmed.text': 'Randevunuz Onaylandı',
    'apptStatus.confirmed.sub':  'Randevunuz salon tarafından onaylandı. Görüşmek üzere!',
    'apptStatus.cancelled.text': 'Randevu İptal Edildi',
    'apptStatus.cancelled.sub':  'Randevunuz iptal edildi. Yeni randevu almak için salonu arayabilirsiniz.',
    'apptStatus.completed.text': 'Randevu Tamamlandı',
    'apptStatus.completed.sub':  'Randevunuzu tamamladınız. Bizi tercih ettiğiniz için teşekkürler!',
    'apptStatus.unknown':        'Bilinmiyor',
    'apptStatus.whatsappShare':  'Randevu takip linkim: ',

    // Salons (public list)
    'salons.searchPh':    'Salon adı veya şehir ara...',
    'salons.searchBtn':   'Ara',
    'salons.loading':     'Salonlar yükleniyor...',
    'salons.notFound':    'Salon bulunamadı',
    'salons.tryAnother':  'Farklı bir arama terimi deneyin.',
    'salons.count':       'salon',
    'salons.bookBtn':     'Randevu Al',
    'salons.footer':      'BerberApp © 2026',

    // Booking (public)
    'booking.loading':          'Salon bilgileri yükleniyor...',
    'booking.notFound':         'Salon Bulunamadı',
    'booking.received':         'Randevunuz Alındı!',
    'booking.receivedSub':      'Randevu bilgileriniz aşağıda.',
    'booking.pendingNote':      '⏳ Randevunuz onay bekliyor. Salon onayladıktan sonra WhatsApp\'a bildirim gelecektir.',
    'booking.lbl.salon':        'Salon',
    'booking.lbl.service':      'Hizmet',
    'booking.lbl.staff':        'Personel',
    'booking.lbl.date':         'Tarih',
    'booking.lbl.time':         'Saat',
    'booking.lbl.price':        'Ücret',
    'booking.successNote':      'Randevunuzu değiştirmek veya iptal etmek için salonumuzu arayabilirsiniz.',
    'booking.ratingApp':        'Randevu Uygulaması',
    'booking.photos':           'Fotoğraflar',
    'booking.location':         'Konum',
    'booking.directions':       'Yol Tarifi',
    'booking.summary':          'Özet',
    'booking.barber':           'Berber',
    'booking.total':            'Toplam',
    'booking.step1':            'Hizmet Seçin',
    'booking.step2':            'Personel Seçin',
    'booking.step3':            'Tarih Seçin',
    'booking.step4':            'Saat Seçin',
    'booking.step5':            'Bilgilerinizi Girin',
    'booking.min':              'dk',
    'booking.noSlots':          'Bu tarih için müsait saat bulunmuyor.',
    'booking.fullNamePh':       'Ad Soyad',
    'booking.fullNameRequired': 'Ad soyad zorunludur.',
    'booking.phoneRequired':    'Telefon numarası zorunludur.',
    'booking.phoneInvalid':     'Geçerli bir telefon numarası girin.',
    'booking.emailPh':          'Email (opsiyonel)',
    'booking.notePh':           'Not ekleyin...',
    'booking.previewTitle':     'Randevu Özeti',
    'booking.dateAndTime':      'Tarih & Saat',
    'booking.submitting':       'Randevu Oluşturuluyor...',
    'booking.submit':           'Randevu Al →',
    'booking.poweredBy':        'BerberApp ile güçlendirildi',
  },

  /* ══════════════════════════════════════ ENGLISH ══════════════════════════════════════ */
  en: {
    'nav.home':         'Home',
    'nav.appointments': 'Appointments',
    'nav.staff':        'Staff',
    'nav.services':     'Services',
    'nav.customers':    'Customers',
    'nav.settings':     'Settings',
    'nav.reports':      'Reports',

    'page.dashboard':    'Dashboard',
    'page.appointments': 'Appointments',
    'page.staff':        'Staff',
    'page.services':     'Services',
    'page.customers':    'Customers',
    'page.settings':     'Settings',
    'page.reports':      'Reports',

    'header.system': 'System Active',

    'dashboard.subtitle':       "Welcome! Here's today's summary.",
    'dashboard.newAppointment': '+ New Appointment',
    'dashboard.todayAppts':     "Today's Appointments",
    'dashboard.viewAll':        'View All →',
    'dashboard.quickActions':   'Quick Actions',
    'dashboard.noAppts':        'No appointments today.',
    'dashboard.q1':             'New Appointment',
    'dashboard.q1sub':          'Create appointment',
    'dashboard.q2':             'Add Customer',
    'dashboard.q2sub':          'New customer record',
    'dashboard.q3':             'Add Staff',
    'dashboard.q3sub':          'New staff record',
    'dashboard.q4':             'Add Service',
    'dashboard.q4sub':          'Define new service',
    'stat.todayAppts':          "Today's Appointments",
    'stat.totalCustomers':      'Total Customers',
    'stat.totalStaff':          'Total Staff',
    'stat.totalServices':       'Total Services',
    'stat.todayRevenue':        "Today's Revenue",

    'status.pending':   'Pending',
    'status.confirmed': 'Confirmed',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.noShow':    'No Show',

    'settings.title':    'Settings',
    'settings.subtitle': 'Manage your salon and account settings',
    'settings.logout':   'Sign Out',

    'settings.salon.card':         'Salon Information',
    'settings.salon.cardSub':      'Information visible to your customers',
    'settings.salon.logo':         'Salon Logo',
    'settings.salon.logoHint':     'JPG, PNG or WebP · Max 5MB',
    'settings.salon.logoUploading':'Uploading...',
    'settings.salon.logoChange':   'Change Logo',
    'settings.salon.logoSelect':   'Select Logo',
    'settings.salon.name':         'Salon Name *',
    'settings.salon.namePh':       'Your salon name',
    'settings.salon.phone':        'Phone',
    'settings.salon.phonePh':      'Phone number',
    'settings.salon.phoneErr':     'Please enter a valid phone number',
    'settings.salon.whatsapp':     'WhatsApp Notification Number',
    'settings.salon.whatsappPh':   'WhatsApp number',
    'settings.salon.whatsappHint': 'You will receive WhatsApp notifications for new appointment requests on this number.',
    'settings.salon.address':      'Address',
    'settings.salon.addressPh':    'Your salon address',
    'settings.salon.themeColor':   'Theme Color',
    'settings.salon.themeHint':    'Set the theme color for your customer booking page',
    'settings.salon.bookingLink':  'Customer Booking Link',
    'settings.salon.save':         'Save',
    'settings.salon.saving':       'Saving...',
    'settings.salon.saved':        'Salon information updated!',
    'settings.salon.custom':       'Custom',

    'settings.photos.card':    'Salon Photos',
    'settings.photos.cardSub': 'Photos visible on your booking page (max 6)',
    'settings.photos.add':     'Add Photo',

    'settings.profile.card':    'Profile Information',
    'settings.profile.cardSub': 'Your account details',

    'settings.password.card':        'Change Password',
    'settings.password.cardSub':     'Update your password for account security',
    'settings.password.current':     'Current Password',
    'settings.password.new':         'New Password',
    'settings.password.confirm':     'Confirm New Password',
    'settings.password.change':      'Change Password',
    'settings.password.changing':    'Changing...',
    'settings.password.changed':     'Password changed successfully!',
    'settings.password.rule.minLen': 'At least 8 characters',
    'settings.password.rule.upper':  'At least 1 uppercase letter (A-Z)',
    'settings.password.rule.number': 'At least 1 number (0-9)',
    'settings.password.noMatch':     'Passwords do not match.',
    'settings.password.tooShort':    'Password must be at least 8 characters.',

    'settings.booking.card':    'Customer Booking Link',
    'settings.booking.cardSub': 'Share this link with your customers',
    'settings.booking.preview': 'Preview',

    // Reports
    'reports.title':           'Reports',
    'reports.subtitle':        'Earnings and appointment analysis',
    'reports.startDate':       'Start Date',
    'reports.endDate':         'End Date',
    'reports.totalEarnings':   'Total Earnings',
    'reports.avgPerAppt':      'Avg. Per Appointment',
    'reports.thisMonth':       'This Month',
    'reports.thisWeek':        'This Week',
    'reports.appt':            'appointments',
    'reports.byStaff':         'Earnings by Staff',
    'reports.byService':       'Earnings by Service',
    'reports.colStaff':        'Staff',
    'reports.colService':      'Service',
    'reports.colTotal':        'Total Earnings',
    'reports.colAppts':        'Appointments',
    'reports.colAvg':          'Average',
    'reports.colPrice':        'Price',
    'reports.colSales':        'Sales Count',
    'reports.noData':          'No data available',
    'reports.byCurrency':      'Earnings by Currency',
    'reports.rateDate':        'Rate date',
    'reports.grandTotal':      'Grand Total (TRY)',

    // Nav sections
    'nav.section.main':  'MAIN MENU',
    'nav.section.other': 'OTHER',
    'nav.logout':        'Sign Out',

    // Common
    'common.loading':          'Loading...',
    'common.copy':             'Copy',
    'common.copied':           'Copied',
    'common.active':           'Active',
    'common.inactive':         'Inactive',
    'common.cancel':           'Cancel',
    'common.save':             'Save',
    'common.saving':           'Saving...',
    'common.update':           'Update',
    'common.edit':             'Edit',
    'common.actions':          'Actions',
    'common.status':           'Status',
    'common.phone':            'Phone',
    'common.fullName':         'Full Name *',
    'common.fullNameRequired': 'Full name is required.',
    'common.date':             'Date',
    'common.closed':           'Closed',
    'common.notes':            'Notes',
    'common.email':            'Email',
    'common.min':              'min',
    'common.hr':               'h',
    'common.error':            'An error occurred.',

    'color.black':  'Black',
    'color.navy':   'Navy',
    'color.purple': 'Purple',
    'color.blue':   'Blue',
    'color.green':  'Green',
    'color.red':    'Red',
    'color.orange': 'Orange',
    'color.pink':   'Pink',
    'color.brown':  'Brown',
    'color.gray':   'Gray',

    // Staff
    'staff.add':          '+ Add Staff',
    'staff.registered':   'staff registered',
    'staff.empty':        'No staff added yet',
    'staff.emptyHint':    'Click the button to add your first staff member.',
    'staff.new':          'New Staff',
    'staff.edit':         'Edit Staff',
    'staff.bio':          'Biography',
    'staff.colBio':       'Bio',
    'staff.workingHours': 'Working Hours',

    // Services
    'services.add':          '+ Add Service',
    'services.registered':   'services defined',
    'services.empty':        'No services added yet',
    'services.emptyHint':    'Click the button to add your first service.',
    'services.new':          'New Service',
    'services.edit':         'Edit Service',
    'services.nameLbl':      'Service Name *',
    'services.nameRequired': 'Service name is required.',
    'services.duration':     'Duration (Minutes) *',
    'services.price':        'Price',
    'services.priceOpt':     '(optional)',
    'services.currency':     'Currency',
    'services.color':        'Color',

    // Appointments
    'appt.new':           '+ New Appointment',
    'appt.count':         'appointments listed',
    'appt.empty':         'No appointments found',
    'appt.emptyHint':     'No appointments for the selected date.',
    'appt.emptyCalendar': 'No appointments for this date',
    'appt.colTime':       'Time',
    'appt.colCustomer':   'Customer',
    'appt.colService':    'Service',
    'appt.colDuration':   'Duration',
    'appt.create':        'Create Appointment',
    'appt.chooseTime':    'Choose Time *',
    'appt.loadingSlots':  'Loading available times...',
    'appt.allStaff':      'All Staff',
    'appt.chooseDate':    'Choose Date',
    'appt.customer':      'Customer *',
    'appt.staff':         'Staff *',
    'appt.service':       'Service *',
    'appt.date':          'Date *',
    'appt.notePh':        'Appointment notes...',

    // Customers
    'customers.add':           '+ Add Customer',
    'customers.registered':    'customers registered',
    'customers.searchPh':      'Search by name, phone or email...',
    'customers.noResults':     'No results found',
    'customers.notFoundFor':   'No customer found for',
    'customers.empty':         'No customers added yet',
    'customers.emptyHint':     'Click the button to add your first customer.',
    'customers.new':           'New Customer',
    'customers.edit':          'Edit Customer',
    'customers.colCustomer':   'Customer',
    'customers.colVisits':     'Total Visits',
    'customers.visit':         'visits',
    'customers.phone':         'Phone *',
    'customers.phoneRequired': 'Phone is required.',
    'customers.emailInvalid':  'Please enter a valid email.',
    'customers.notePh':        'Notes about the customer...',

    // Appointment Status (public)
    'apptStatus.notFound':       'Appointment Not Found',
    'apptStatus.notFoundMsg':    'Appointment not found.',
    'apptStatus.saveLink':       '📎 Save this link',
    'apptStatus.saveLinkDesc':   'You can track your appointment status here.',
    'apptStatus.copyLink':       '📋 Copy Link',
    'apptStatus.pending.text':   'Awaiting Approval',
    'apptStatus.pending.sub':    'Waiting for salon approval. You will be notified shortly.',
    'apptStatus.confirmed.text': 'Appointment Confirmed',
    'apptStatus.confirmed.sub':  'Your appointment has been confirmed by the salon. See you soon!',
    'apptStatus.cancelled.text': 'Appointment Cancelled',
    'apptStatus.cancelled.sub':  'Your appointment was cancelled. You can call the salon to make a new one.',
    'apptStatus.completed.text': 'Appointment Completed',
    'apptStatus.completed.sub':  'Thank you for choosing us! Your appointment is complete.',
    'apptStatus.unknown':        'Unknown',
    'apptStatus.whatsappShare':  'My appointment tracking link: ',

    // Salons (public list)
    'salons.searchPh':    'Search by salon name or city...',
    'salons.searchBtn':   'Search',
    'salons.loading':     'Loading salons...',
    'salons.notFound':    'Salon not found',
    'salons.tryAnother':  'Try a different search term.',
    'salons.count':       'salons',
    'salons.bookBtn':     'Book Appointment',
    'salons.footer':      'BerberApp © 2026',

    // Booking (public)
    'booking.loading':          'Loading salon info...',
    'booking.notFound':         'Salon Not Found',
    'booking.received':         'Appointment Received!',
    'booking.receivedSub':      'Your appointment details are below.',
    'booking.pendingNote':      '⏳ Your appointment is pending. You will receive a WhatsApp notification after the salon confirms.',
    'booking.lbl.salon':        'Salon',
    'booking.lbl.service':      'Service',
    'booking.lbl.staff':        'Staff',
    'booking.lbl.date':         'Date',
    'booking.lbl.time':         'Time',
    'booking.lbl.price':        'Price',
    'booking.successNote':      'You can call our salon to change or cancel your appointment.',
    'booking.ratingApp':        'Booking App',
    'booking.photos':           'Photos',
    'booking.location':         'Location',
    'booking.directions':       'Get Directions',
    'booking.summary':          'Summary',
    'booking.barber':           'Barber',
    'booking.total':            'Total',
    'booking.step1':            'Choose a Service',
    'booking.step2':            'Choose Staff',
    'booking.step3':            'Choose a Date',
    'booking.step4':            'Choose a Time',
    'booking.step5':            'Enter Your Details',
    'booking.min':              'min',
    'booking.noSlots':          'No available slots for this date.',
    'booking.fullNamePh':       'Full Name',
    'booking.fullNameRequired': 'Full name is required.',
    'booking.phoneRequired':    'Phone number is required.',
    'booking.phoneInvalid':     'Please enter a valid phone number.',
    'booking.emailPh':          'Email (optional)',
    'booking.notePh':           'Add a note...',
    'booking.previewTitle':     'Appointment Summary',
    'booking.dateAndTime':      'Date & Time',
    'booking.submitting':       'Creating Appointment...',
    'booking.submit':           'Book Appointment →',
    'booking.poweredBy':        'Powered by BerberApp',
  },

  /* ══════════════════════════════════════ РУССКИЙ ══════════════════════════════════════ */
  ru: {
    'nav.home':         'Главная',
    'nav.appointments': 'Записи',
    'nav.staff':        'Персонал',
    'nav.services':     'Услуги',
    'nav.customers':    'Клиенты',
    'nav.settings':     'Настройки',
    'nav.reports':      'Отчёты',

    'page.dashboard':    'Панель управления',
    'page.appointments': 'Записи',
    'page.staff':        'Персонал',
    'page.services':     'Услуги',
    'page.customers':    'Клиенты',
    'page.settings':     'Настройки',
    'page.reports':      'Отчёты',

    'header.system': 'Система активна',

    'dashboard.subtitle':       'Добро пожаловать! Сводка за сегодня.',
    'dashboard.newAppointment': '+ Новая запись',
    'dashboard.todayAppts':     'Записи на сегодня',
    'dashboard.viewAll':        'Смотреть все →',
    'dashboard.quickActions':   'Быстрые действия',
    'dashboard.noAppts':        'На сегодня записей нет.',
    'dashboard.q1':             'Новая запись',
    'dashboard.q1sub':          'Создать запись',
    'dashboard.q2':             'Добавить клиента',
    'dashboard.q2sub':          'Новая запись клиента',
    'dashboard.q3':             'Добавить сотрудника',
    'dashboard.q3sub':          'Новая запись сотрудника',
    'dashboard.q4':             'Добавить услугу',
    'dashboard.q4sub':          'Создать новую услугу',
    'stat.todayAppts':          'Записи на сегодня',
    'stat.totalCustomers':      'Всего клиентов',
    'stat.totalStaff':          'Всего сотрудников',
    'stat.totalServices':       'Всего услуг',
    'stat.todayRevenue':        'Доход за сегодня',

    'status.pending':   'Ожидает',
    'status.confirmed': 'Подтверждено',
    'status.completed': 'Завершено',
    'status.cancelled': 'Отменено',
    'status.noShow':    'Не пришёл',

    'settings.title':    'Настройки',
    'settings.subtitle': 'Управляйте настройками салона и аккаунта',
    'settings.logout':   'Выйти',

    'settings.salon.card':         'Информация о салоне',
    'settings.salon.cardSub':      'Информация, видимая вашим клиентам',
    'settings.salon.logo':         'Логотип салона',
    'settings.salon.logoHint':     'JPG, PNG или WebP · Макс 5MB',
    'settings.salon.logoUploading':'Загрузка...',
    'settings.salon.logoChange':   'Изменить логотип',
    'settings.salon.logoSelect':   'Выбрать логотип',
    'settings.salon.name':         'Название салона *',
    'settings.salon.namePh':       'Название вашего салона',
    'settings.salon.phone':        'Телефон',
    'settings.salon.phonePh':      'Номер телефона',
    'settings.salon.phoneErr':     'Введите корректный номер телефона',
    'settings.salon.whatsapp':     'Номер WhatsApp для уведомлений',
    'settings.salon.whatsappPh':   'Номер WhatsApp',
    'settings.salon.whatsappHint': 'На этот номер будут приходить уведомления о новых запросах на запись.',
    'settings.salon.address':      'Адрес',
    'settings.salon.addressPh':    'Адрес вашего салона',
    'settings.salon.themeColor':   'Цвет темы',
    'settings.salon.themeHint':    'Установите цвет темы для страницы записи клиентов',
    'settings.salon.bookingLink':  'Ссылка для записи клиентов',
    'settings.salon.save':         'Сохранить',
    'settings.salon.saving':       'Сохранение...',
    'settings.salon.saved':        'Информация о салоне обновлена!',
    'settings.salon.custom':       'Свой',

    'settings.photos.card':    'Фотографии салона',
    'settings.photos.cardSub': 'Фотографии на странице записи (макс. 6)',
    'settings.photos.add':     'Добавить фото',

    'settings.profile.card':    'Данные профиля',
    'settings.profile.cardSub': 'Информация о вашем аккаунте',

    'settings.password.card':        'Изменить пароль',
    'settings.password.cardSub':     'Обновите пароль для безопасности аккаунта',
    'settings.password.current':     'Текущий пароль',
    'settings.password.new':         'Новый пароль',
    'settings.password.confirm':     'Подтвердите новый пароль',
    'settings.password.change':      'Изменить пароль',
    'settings.password.changing':    'Изменение...',
    'settings.password.changed':     'Пароль успешно изменён!',
    'settings.password.rule.minLen': 'Не менее 8 символов',
    'settings.password.rule.upper':  'Не менее 1 заглавной буквы (A-Z)',
    'settings.password.rule.number': 'Не менее 1 цифры (0-9)',
    'settings.password.noMatch':     'Пароли не совпадают.',
    'settings.password.tooShort':    'Пароль должен содержать не менее 8 символов.',

    'settings.booking.card':    'Ссылка для записи клиентов',
    'settings.booking.cardSub': 'Поделитесь этой ссылкой с клиентами',
    'settings.booking.preview': 'Просмотр',

    // Reports
    'reports.title':           'Отчёты',
    'reports.subtitle':        'Анализ доходов и записей',
    'reports.startDate':       'Дата начала',
    'reports.endDate':         'Дата окончания',
    'reports.totalEarnings':   'Общий доход',
    'reports.avgPerAppt':      'Сред. за запись',
    'reports.thisMonth':       'Этот месяц',
    'reports.thisWeek':        'Эта неделя',
    'reports.appt':            'запис(ей)',
    'reports.byStaff':         'Доход по сотрудникам',
    'reports.byService':       'Доход по услугам',
    'reports.colStaff':        'Сотрудник',
    'reports.colService':      'Услуга',
    'reports.colTotal':        'Общий доход',
    'reports.colAppts':        'Записей',
    'reports.colAvg':          'Среднее',
    'reports.colPrice':        'Цена',
    'reports.colSales':        'Количество продаж',
    'reports.noData':          'Нет данных',
    'reports.byCurrency':      'Доход по валютам',
    'reports.rateDate':        'Дата курса',
    'reports.grandTotal':      'Итого (TRY)',

    // Nav sections
    'nav.section.main':  'ГЛАВНОЕ МЕНЮ',
    'nav.section.other': 'ДРУГОЕ',
    'nav.logout':        'Выйти',

    // Common
    'common.loading':          'Загрузка...',
    'common.copy':             'Копировать',
    'common.copied':           'Скопировано',
    'common.active':           'Активный',
    'common.inactive':         'Неактивный',
    'common.cancel':           'Отмена',
    'common.save':             'Сохранить',
    'common.saving':           'Сохранение...',
    'common.update':           'Обновить',
    'common.edit':             'Редактировать',
    'common.actions':          'Действия',
    'common.status':           'Статус',
    'common.phone':            'Телефон',
    'common.fullName':         'Имя и Фамилия *',
    'common.fullNameRequired': 'Имя и фамилия обязательны.',
    'common.date':             'Дата',
    'common.closed':           'Закрыто',
    'common.notes':            'Заметки',
    'common.email':            'Email',
    'common.min':              'мин',
    'common.hr':               'ч',
    'common.error':            'Произошла ошибка.',

    'color.black':  'Чёрный',
    'color.navy':   'Тёмно-синий',
    'color.purple': 'Фиолетовый',
    'color.blue':   'Синий',
    'color.green':  'Зелёный',
    'color.red':    'Красный',
    'color.orange': 'Оранжевый',
    'color.pink':   'Розовый',
    'color.brown':  'Коричневый',
    'color.gray':   'Серый',

    // Staff
    'staff.add':          '+ Добавить сотрудника',
    'staff.registered':   'сотрудник(ов) зарегистрировано',
    'staff.empty':        'Сотрудники ещё не добавлены',
    'staff.emptyHint':    'Нажмите кнопку, чтобы добавить первого сотрудника.',
    'staff.new':          'Новый сотрудник',
    'staff.edit':         'Редактировать сотрудника',
    'staff.bio':          'Биография',
    'staff.colBio':       'Биография',
    'staff.workingHours': 'Рабочие часы',

    // Services
    'services.add':          '+ Добавить услугу',
    'services.registered':   'услуг определено',
    'services.empty':        'Услуги ещё не добавлены',
    'services.emptyHint':    'Нажмите кнопку, чтобы добавить первую услугу.',
    'services.new':          'Новая услуга',
    'services.edit':         'Редактировать услугу',
    'services.nameLbl':      'Название услуги *',
    'services.nameRequired': 'Название услуги обязательно.',
    'services.duration':     'Длительность (мин) *',
    'services.price':        'Цена',
    'services.priceOpt':     '(необязательно)',
    'services.currency':     'Валюта',
    'services.color':        'Цвет',

    // Appointments
    'appt.new':           '+ Новая запись',
    'appt.count':         'запис(ей) показано',
    'appt.empty':         'Записи не найдены',
    'appt.emptyHint':     'На выбранную дату записей нет.',
    'appt.emptyCalendar': 'На эту дату записей нет',
    'appt.colTime':       'Время',
    'appt.colCustomer':   'Клиент',
    'appt.colService':    'Услуга',
    'appt.colDuration':   'Длит.',
    'appt.create':        'Создать запись',
    'appt.chooseTime':    'Выберите время *',
    'appt.loadingSlots':  'Загрузка доступных слотов...',
    'appt.allStaff':      'Весь персонал',
    'appt.chooseDate':    'Выберите дату',
    'appt.customer':      'Клиент *',
    'appt.staff':         'Сотрудник *',
    'appt.service':       'Услуга *',
    'appt.date':          'Дата *',
    'appt.notePh':        'Заметки к записи...',

    // Customers
    'customers.add':           '+ Добавить клиента',
    'customers.registered':    'клиент(ов) зарегистрировано',
    'customers.searchPh':      'Поиск по имени, телефону или email...',
    'customers.noResults':     'Результаты не найдены',
    'customers.notFoundFor':   'Клиент не найден для',
    'customers.empty':         'Клиенты ещё не добавлены',
    'customers.emptyHint':     'Нажмите кнопку, чтобы добавить первого клиента.',
    'customers.new':           'Новый клиент',
    'customers.edit':          'Редактировать клиента',
    'customers.colCustomer':   'Клиент',
    'customers.colVisits':     'Всего визитов',
    'customers.visit':         'визит(ов)',
    'customers.phone':         'Телефон *',
    'customers.phoneRequired': 'Телефон обязателен.',
    'customers.emailInvalid':  'Введите корректный email.',
    'customers.notePh':        'Заметки о клиенте...',

    // Appointment Status (public)
    'apptStatus.notFound':       'Запись не найдена',
    'apptStatus.notFoundMsg':    'Запись не найдена.',
    'apptStatus.saveLink':       '📎 Сохраните эту ссылку',
    'apptStatus.saveLinkDesc':   'Здесь вы можете отслеживать статус записи.',
    'apptStatus.copyLink':       '📋 Копировать ссылку',
    'apptStatus.pending.text':   'Ожидает подтверждения',
    'apptStatus.pending.sub':    'Ожидаем подтверждения от салона. Вы получите уведомление в ближайшее время.',
    'apptStatus.confirmed.text': 'Запись подтверждена',
    'apptStatus.confirmed.sub':  'Ваша запись подтверждена салоном. До встречи!',
    'apptStatus.cancelled.text': 'Запись отменена',
    'apptStatus.cancelled.sub':  'Ваша запись была отменена. Позвоните в салон для новой записи.',
    'apptStatus.completed.text': 'Запись завершена',
    'apptStatus.completed.sub':  'Спасибо, что выбрали нас! Запись завершена.',
    'apptStatus.unknown':        'Неизвестно',
    'apptStatus.whatsappShare':  'Ссылка для отслеживания записи: ',

    // Salons (public list)
    'salons.searchPh':    'Поиск по названию или городу...',
    'salons.searchBtn':   'Найти',
    'salons.loading':     'Загрузка салонов...',
    'salons.notFound':    'Салон не найден',
    'salons.tryAnother':  'Попробуйте другой поисковый запрос.',
    'salons.count':       'салон(ов)',
    'salons.bookBtn':     'Записаться',
    'salons.footer':      'BerberApp © 2026',

    // Booking (public)
    'booking.loading':          'Загрузка информации о салоне...',
    'booking.notFound':         'Салон не найден',
    'booking.received':         'Запись принята!',
    'booking.receivedSub':      'Ваши данные о записи ниже.',
    'booking.pendingNote':      '⏳ Ваша запись ожидает подтверждения. Вы получите уведомление в WhatsApp после подтверждения салоном.',
    'booking.lbl.salon':        'Салон',
    'booking.lbl.service':      'Услуга',
    'booking.lbl.staff':        'Сотрудник',
    'booking.lbl.date':         'Дата',
    'booking.lbl.time':         'Время',
    'booking.lbl.price':        'Стоимость',
    'booking.successNote':      'Вы можете позвонить в салон для изменения или отмены записи.',
    'booking.ratingApp':        'Приложение для записи',
    'booking.photos':           'Фотографии',
    'booking.location':         'Местоположение',
    'booking.directions':       'Маршрут',
    'booking.summary':          'Сводка',
    'booking.barber':           'Мастер',
    'booking.total':            'Итого',
    'booking.step1':            'Выберите услугу',
    'booking.step2':            'Выберите сотрудника',
    'booking.step3':            'Выберите дату',
    'booking.step4':            'Выберите время',
    'booking.step5':            'Введите ваши данные',
    'booking.min':              'мин',
    'booking.noSlots':          'На эту дату нет доступных слотов.',
    'booking.fullNamePh':       'Имя и Фамилия',
    'booking.fullNameRequired': 'Имя и фамилия обязательны.',
    'booking.phoneRequired':    'Номер телефона обязателен.',
    'booking.phoneInvalid':     'Введите корректный номер телефона.',
    'booking.emailPh':          'Email (необязательно)',
    'booking.notePh':           'Добавить заметку...',
    'booking.previewTitle':     'Краткая информация о записи',
    'booking.dateAndTime':      'Дата и время',
    'booking.submitting':       'Создание записи...',
    'booking.submit':           'Записаться →',
    'booking.poweredBy':        'Работает на BerberApp',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly lang = signal<Lang>((localStorage.getItem('lang') as Lang) || 'tr');

  setLang(l: Lang): void {
    this.lang.set(l);
    localStorage.setItem('lang', l);
  }

  t(key: string): string {
    return T[this.lang()][key] ?? key;
  }

  get dateLocale(): string {
    return { tr: 'tr-TR', en: 'en-US', ru: 'ru-RU' }[this.lang()];
  }

  get langLabel(): string {
    return { tr: 'TR', en: 'EN', ru: 'RU' }[this.lang()];
  }
}
